const BASE_DATA_DIR = 'assets/data/';
export const MUSHAF_DATA_DIR = BASE_DATA_DIR + 'mushaf/';
export const TAFSIR_MAKHLOUF_DATA_DIR = BASE_DATA_DIR + 'tafsir/makhlouf/';
export const QURAN_PAGE_CONTENT_FILE_EXTENSION = '.content';
export const QURAN_PAGE_METADATA_FILE_EXTENSION = '.metadata';
export const PAGE_NUMBER_PARAM = 'pageNumber';
export const GOZE = 'goze';
export const HEZB = 'hezb';
export const SURAH_NAME = 'suranName';